import { WINE1 } from "../assets/images";

export const COLLECTION_CARD = [
  {
    id: 1,
    title: "PLATINUM",
    rp: "1 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 2,
    title: "PLATINUM",
    rp: "2 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 3,
    title: "PLATINUM",
    rp: "3 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 4,
    title: "Gold",
    rp: "4 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "Gold",
    rp: "5 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "Gold",
    rp: "6 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "silver",
    rp: "7 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "silver",
    rp: "8 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "silver",
    rp: "9 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "10 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "11 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
  {
    id: 5,
    title: "PLATINUM",
    rp: "12 RP",
    wine: WINE1,
    wine_value: "Del Maguey “San Jose Rio Minas” Mezcal 750ml",
    msrp: "$4,154",
    owner: "Joannejujubeat",
  },
];
